# Generated by Django 4.2.1 on 2023-12-08 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GearBox_app', '0002_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=False)),
                ('Title', models.CharField(max_length=255)),
                ('Start_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 8, 54, 45, 727425, tzinfo=datetime.timezone.utc))),
                ('End_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 8, 54, 45, 727425, tzinfo=datetime.timezone.utc))),
                ('report_to_origin', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 8, 54, 45, 727425, tzinfo=datetime.timezone.utc))),
                ('Status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('dispacted', 'Dispatched'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='incomplete', max_length=20)),
                ('Origin', models.CharField(max_length=255)),
                ('Recurring', models.CharField(max_length=255)),
                ('Staff_Notes', models.CharField(max_length=1024)),
                ('Created_by', models.CharField(max_length=255)),
                ('Created_time', models.TimeField(default=datetime.datetime(2023, 12, 8, 8, 54, 45, 727425, tzinfo=datetime.timezone.utc))),
                ('preStartWindow', models.CharField(default='15', max_length=2)),
                ('truckNo', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
            ],
        ),
    ]
