# Generated by Django 4.2.1 on 2023-12-09 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0003_alter_clienttruckconnection_startdate_and_more'),
        ('Appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='truckNo',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 9, 12, 3, 18, 211072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 3, 18, 211072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 3, 18, 211072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 3, 18, 211072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AppointmentTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.appointment')),
                ('truckNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.admintruck')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.appointment')),
                ('driverName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
            ],
        ),
    ]
