# Generated by Django 4.2.1 on 2023-12-26 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0004_appointment_shifttype_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitForWork', models.BooleanField(default=False)),
                ('vehicleStatus', models.BooleanField(default=False)),
                ('vehiclePaper', models.BooleanField(default=False)),
                ('comment', models.CharField(default='', max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 26, 6, 52, 2, 686944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 6, 52, 2, 685947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 6, 52, 2, 685947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 6, 52, 2, 685947, tzinfo=datetime.timezone.utc)),
        ),
    ]
