# Generated by Django 4.2.2 on 2023-12-26 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0006_alter_clienttruckconnection_startdate_and_more'),
        ('Appointment_app', '0007_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestart',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 26, 7, 20, 55, 815955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 7, 20, 55, 815955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 7, 20, 55, 815955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 7, 20, 55, 815955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestart',
            name='curDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 7, 20, 55, 816957, tzinfo=datetime.timezone.utc)),
        ),
    ]
