# Generated by Django 4.2.1 on 2024-01-02 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0008_prestart_driver_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 2, 15, 13, 16, 219999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 13, 16, 219999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 13, 16, 219999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 13, 16, 219999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestart',
            name='curDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 13, 16, 223391, tzinfo=datetime.timezone.utc)),
        ),
    ]
