# Generated by Django 4.2.1 on 2023-12-09 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='managerName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='location',
            name='personOnName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 12, 3, 34, 303404, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
