# Generated by Django 4.2.1 on 2023-12-09 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0003_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='baseplant',
            name='basePlantType',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 16, 29, 31, 945105, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
