# Generated by Django 4.2.1 on 2023-12-10 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0007_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holcimdocket',
            name='truckNo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 12, 58, 20, 992477, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='holcimtrip',
            name='truckNo',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
