# Generated by Django 4.2.1 on 2023-12-13 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0008_holcimdocket_truckno_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 7, 15, 29, 573671, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='holcimdocket',
            unique_together={('jobNo', 'ticketed', 'tripId')},
        ),
    ]
