# Generated by Django 4.2.1 on 2023-12-14 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0011_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 14, 7, 17, 47, 79259, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
