# Generated by Django 4.2.1 on 2023-12-14 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0012_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='partially',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 14, 10, 49, 46, 616955, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='loadSheet',
            field=models.FileField(blank=True, null=True, upload_to='static/img/finalloadSheet'),
        ),
    ]
