# Generated by Django 4.2.1 on 2023-12-22 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0013_drivertrip_partially_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 22, 9, 13, 16, 914792, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='holcimdocket',
            unique_together={('jobNo', 'ticketedDate', 'tripId')},
        ),
    ]
