# Generated by Django 4.2.1 on 2023-12-22 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0014_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 22, 9, 27, 48, 971953, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='jobNo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='leadDistance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='orderNo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='returnDistance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='slump',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='timeOnSite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='timeToDepart',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='timeToSite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='totalDistance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='totalTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='truckNo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='waitTimeBetweenJob',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='waitingTime',
            field=models.FloatField(default=0),
        ),
    ]
