# Generated by Django 4.2.1 on 2023-12-27 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0017_rcti_blowback_rcti_blowbackcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcti',
            name='paidQty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rcti',
            name='unit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 13, 6, 34, 190033, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
