# Generated by Django 4.2.1 on 2023-12-27 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0018_rcti_paidqty_rcti_unit_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 13, 36, 23, 267403, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
