# Generated by Django 4.2.1 on 2023-12-27 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0019_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 13, 46, 12, 38999, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='rcti',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
