# Generated by Django 4.2.1 on 2023-12-28 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0021_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 7, 6, 23, 534459, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
