# Generated by Django 4.2.1 on 2023-12-28 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0023_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcti',
            old_name='surcharge_duration',
            new_name='surcharge',
        ),
        migrations.RenameField(
            model_name='rcti',
            old_name='surcharge_fixed_normal',
            new_name='surchargeCost',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surchargeUnit',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_public_holiday',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_sunday',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekday',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekdayCost',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekdayGSTPayable',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekdayTotal',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekdayTotalExGST',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekend',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekendCost',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekendGSTPayable',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekendTotal',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_fixed_weekendTotalExGST',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_per_cubic_meters_normal',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_per_cubic_meters_public_holiday',
        ),
        migrations.RemoveField(
            model_name='rcti',
            name='surcharge_per_cubic_meters_sunday',
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 13, 41, 3, 953852, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
