# Generated by Django 4.2.1 on 2024-01-03 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0024_rename_surcharge_duration_rcti_surcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationreport',
            name='clientName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='escalationAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 8, 3, 15, 757478, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='endTime',
            field=models.BooleanField(default=False),
        ),
    ]
