# Generated by Django 4.2.1 on 2024-01-03 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0025_reconciliationreport_clientname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='comment2',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='dispute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 16, 56, 17, 575665, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='endTime',
            field=models.CharField(max_length=200),
        ),
    ]
