# Generated by Django 4.2.1 on 2024-01-04 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0026_drivertrip_comment2_drivertrip_dispute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 7, 4, 46, 716531, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='RctiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.DateField()),
                ('gstPayable', models.FloatField(default=0)),
                ('totalExGST', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('fileName', models.CharField(default='', max_length=255)),
            ],
            options={
                'unique_together': {('reportDate', 'total', 'fileName')},
            },
        ),
    ]
