# Generated by Django 4.2.1 on 2024-01-04 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0027_alter_driverdocket_shiftdate_rctireport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcti',
            name='rctiReport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Account_app.rctireport'),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 7, 8, 23, 490524, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
