# Generated by Django 4.2.1 on 2024-01-04 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0028_rcti_rctireport_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 7, 11, 14, 835169, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='rcti',
            name='rctiReport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account_app.rctireport'),
        ),
    ]
