# Generated by Django 4.2.1 on 2024-01-05 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0033_rctiexpense_rctireport_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rctiexpense',
            name='rctiReport',
        ),
        migrations.AddField(
            model_name='rcti',
            name='otherDescription',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 12, 10, 12, 544310, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
