# Generated by Django 4.2.1 on 2024-01-06 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0010_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0034_remove_rctiexpense_rctireport_rcti_otherdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rctireport',
            name='clientName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client'),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 6, 31, 23, 572165, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='rcti',
            name='others',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
