# Generated by Django 4.2.1 on 2024-01-06 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0011_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0035_rctireport_clientname_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rctiexpense',
            name='clientName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client'),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 6, 49, 59, 416102, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
