# Generated by Django 4.2.1 on 2024-01-06 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0037_alter_driverdocket_shiftdate_rctiadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rctiadjustment',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 9, 35, 34, 323357, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
