# Generated by Django 4.2.2 on 2024-01-07 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0039_escalation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 13, 35, 38, 66953, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='remark',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
