# Generated by Django 4.2.2 on 2024-01-07 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0040_alter_driverdocket_shiftdate_alter_escalation_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 13, 36, 4, 154343, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='errorId',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
