# Generated by Django 4.2.1 on 2024-01-07 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0042_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 13, 48, 29, 634525, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
