# Generated by Django 4.2.1 on 2024-01-07 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0044_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='docketDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 14, 40, 46, 555089, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
