# Generated by Django 4.2.2 on 2024-01-07 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0046_escalationmail_mailsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationmail',
            name='mailAttachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 18, 15, 29, 4917, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
